export const TABLE_LIST_REQUEST = "TABLE_LIST_REQUEST";
export const TABLE_LIST_SUCCESS = "TABLE_LIST_SUCCESS";
export const TABLE_LIST_FAIL = "TABLE_LIST_FAIL";

export const TABLE_LIST_ALL_REQUEST = "TABLE_LIST_ALL_REQUEST";
export const TABLE_LIST_ALL_SUCCESS = "TABLE_LIST_ALL_SUCCESS";
export const TABLE_LIST_ALL_FAIL = "TABLE_LIST_ALL_FAIL";
export const TABLE_LIST_ALL_RESET = "TABLE_LIST_ALL_RESET";

export const TABLE_FIND_REQUEST = "TABLE_FIND_REQUEST";
export const TABLE_FIND_SUCCESS = "TABLE_FIND_SUCCESS";
export const TABLE_FIND_FAIL = "TABLE_FIND_FAIL";

export const TABLE_UPDATE_REQUEST = "TABLE_UPDATE_REQUEST";
export const TABLE_UPDATE_SUCCESS = "TABLE_UPDATE_SUCCESS";
export const TABLE_UPDATE_FAIL = "TABLE_UPDATE_FAIL";

export const TABLE_REMOVE_REQUEST = "TABLE_REMOVE_REQUEST";
export const TABLE_REMOVE_SUCCESS = "TABLE_REMOVE_SUCCESS";
export const TABLE_REMOVE_FAIL = "TABLE_REMOVE_FAIL";
